// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cn/kents/java/proto/Hello.proto

package cn.kents.java.proto;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_kents_java_proto_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_kents_java_proto_Hello_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037cn/kents/java/proto/Hello.proto\022\023cn.ke" +
      "nts.java.proto\"?\n\005Hello\022\021\n\004name\030\001 \001(\tH\000\210" +
      "\001\001\022\014\n\004mail\030\002 \003(\t\022\014\n\004data\030\003 \001(\014B\007\n\005_nameB" +
      "#\n\023cn.kents.java.protoB\nHelloProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_kents_java_proto_Hello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_kents_java_proto_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_kents_java_proto_Hello_descriptor,
        new java.lang.String[] { "Name", "Mail", "Data", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
