// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cn/kents/java/proto/Hello.proto

package cn.kents.java.proto;

public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.kents.java.proto.Hello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
